### ISSUE TITLE
Change the behavior of available services

### ISSUE THREAD

**Issue by kpachhai** [tuum-tech/vouch-capsule#11]
Currently, if a user doesn't have phone number set on their DID, the phone validation service is greyed out. We need to change this behavior so the following happens:
- Whenever a user clicks on a service for which the information is not available(eg. selecting phone validation but user doesn't have phone number set for their DID), an alert should pop-up to let the user know that this service is unavailable and that they need to relogin after they set their phone number on their DID profile. Same goes for name validation logic as well

**Comment by mfaizanatiq** [comment]
![image](https://user-images.githubusercontent.com/7628901/82984801-ea089b00-a003-11ea-87bf-7c20c666aaad.png)

**Comment by wakqasahmed** [comment]
@kpachhai This issue require two part validation, please confirm:

1) User didn't give permission to retrieve this information so we ask user to allow retrieving this information (e.g. mobile as shown in the graphic above)
2) The information is retrieved but we currently do not have any validator for that information (e.g. "Mobile") - What should we show in this case?

**Comment by kpachhai** [comment]
"There are currently no validators available to validate phone numbers"
