### ISSUE TITLE
Redesign the request page to display information nicely

### ISSUE THREAD

**Issue by kpachhai** [tuum-tech/vouch-capsule#12]
Currently, we just print out field and its value whenever a user clicks on a particular request that has been completed. Let's change the design a bit to include the following in a nice format:

- Request ID
- Appropriate fields that were validated with DID
- DID
- Status
- Validator
- Validation Service(eg. Email Validation, Name validation, etc)
- Last Updated

If status is "Pending", showing the above fields is good enough

If status is "Success", we need to show additional fields in addition to the above fields:
- Verified Credential as it appears(this is the verified credential that will eventually be saved to user's Identity app after something is validated) 

Example of verified credential:
![image](https://user-images.githubusercontent.com/2739378/82926956-ef0b1300-9f4d-11ea-8a21-088b7e6ccbf6.png)

**Comment by mfaizanatiq** [comment]
01 Waiting for Approval 
![image](https://user-images.githubusercontent.com/7628901/82979775-f3d8d100-9ff8-11ea-800b-96c674f5a96a.png)

02 Approved
![image](https://user-images.githubusercontent.com/7628901/82979803-06eba100-9ff9-11ea-9e9a-43332bfaca0d.png)

03 Rejected
![image](https://user-images.githubusercontent.com/7628901/82979857-271b6000-9ff9-11ea-90ac-545a900fb315.png)

**Comment by mfaizanatiq** [comment]
01 Waiting 4 Approval
02 Approved
03 Rejected

![image](https://user-images.githubusercontent.com/7628901/82980309-3222c000-9ffa-11ea-8bfe-d2114084088a.png)
