### ISSUE TITLE
Implement a button for each request that will allow users to save the verified credential to Identity app

### ISSUE THREAD

**Issue by kpachhai** [tuum-tech/vouch-capsule#15]
Check out https://developer.elastos.org/build/elastos_scheme/#import-credentials-command on how to implement this onto vouch app

**Comment by mfaizanatiq** [comment]
![image](https://user-images.githubusercontent.com/7628901/82980512-b07f6200-9ffa-11ea-912d-238045e2e065.png)

**Comment by wakqasahmed** [comment]
Missed to create branch, hence committed to dev itself.

Have a look at this commit
https://github.com/tuum-tech/vouch-capsule/commit/3fa61c46337520a0f25fbef77d011e1f4e3cf2bf
