### ISSUE TITLE
Design popup

### ISSUE THREAD

**Issue by kpachhai** [tuum-tech/vouch-capsule#41]
We need to create a template design for popups that we can use throughout the app.
Take a look at the following current popups below and let's come up with a nice looking popup design that we will then implement in the app.

![image](https://user-images.githubusercontent.com/2739378/84807918-f1551000-afd5-11ea-814e-d48d90054aa2.png)

![image](https://user-images.githubusercontent.com/2739378/84807928-f5812d80-afd5-11ea-8fe4-7b7ccebe0797.png)

**Comment by mfaizanatiq** [comment]
Could you please let me know what other error messages besides these we need to show?

I will design the graphics for where ever possible.

@kpachhai  @wakqasahmed

**Comment by kpachhai** [comment]
There will be not just error messages but also regular popups. So let's create multiple popup templates for all scenarios: one template for normal popup, one template for success popup and one template for error pop-up. This way u don't need to know the actual content inside these popups. Rather we just need to design the 3 templates for the above 3 scenarios

**Comment by kpachhai** [comment]
We can take those templates and create as many different popups as we want after that by changing the content ourselves

**Comment by mfaizanatiq** [comment]
ok got it, so you need general ones that can be used in the following scenarios.
1. Normal (Information, notification or general pop-up)
2. Success
3. Errors

**Comment by kpachhai** [comment]
yes sir

**Comment by mfaizanatiq** [comment]
Hi Kiran,

Here look at these alert boxes

![image](https://user-images.githubusercontent.com/7628901/85173286-efb07400-b283-11ea-9dbe-1f940883124a.png)

**Comment by mfaizanatiq** [comment]
Now in context.

![image](https://user-images.githubusercontent.com/7628901/85173311-035bda80-b284-11ea-8639-7488e4bd69b4.png)

![image](https://user-images.githubusercontent.com/7628901/85173318-08208e80-b284-11ea-9836-580488ef5439.png)

![image](https://user-images.githubusercontent.com/7628901/85173322-0c4cac00-b284-11ea-9192-33402c45bd13.png)

![image](https://user-images.githubusercontent.com/7628901/85173330-1078c980-b284-11ea-89f4-5364176144d9.png)

**Comment by kpachhai** [comment]
I like it!
