### ISSUE TITLE
Allow user to remove their Pending requests

### ISSUE THREAD

**Issue by kpachhai** [tuum-tech/vouch-capsule#46]
Sometimes, the user may accidentally request the same request multiple times. In such times, we should let the user easily remove the request if it's in pending state. If the request is succeeded, it cannot be removed.

**Comment by wakqasahmed** [comment]
Do we have an endpoint for this?

**Comment by kpachhai** [comment]
Not yet. It has an issue currently. https://github.com/tuum-tech/vouch-restapi-backend/issues/14

**Comment by kpachhai** [comment]
Status on this?
