### ISSUE TITLE
Alert the user if the user is trying to submit the same request

### ISSUE THREAD

**Issue by kpachhai** [tuum-tech/vouch-capsule#47]
There is now a check on rest API side where if the same request is sent within 10 minutes of the first request, no new request is generated. Rather, the same request that's already recorded on the database is returned with the key "duplicate" set to True.
If the value for "duplicate" is set to True, alert the user with a popup saying the user has already submitted a similar request in the last 10 minutes. No new request was submitted.

**Comment by wakqasahmed** [comment]
Missed to create branch, hence committed to dev itself.

Have a look at this commit
https://github.com/tuum-tech/vouch-capsule/commit/8ffaa4b8a6e84cac24c6093fd266cb68acfc417a
