### ISSUE TITLE
Request "avatar" during sign in and refresh credentials

### ISSUE THREAD

**Issue by kpachhai** [tuum-tech/vouch-capsule#62]
Currently, the user is given an option to select their name and email while signing in.

We should make the following changes:
- Mandatory Data Access: Identity 
- Optional Data Access: Avatar, Name, Email Address

Update the profile page to show this avatar. If avatar was not selected, show the default avatar

**Comment by mfaizanatiq** [comment]
### Home Screen
![image](https://user-images.githubusercontent.com/7628901/88452516-7a325780-ce70-11ea-9058-91634b6ceb79.png)

### Profile
![image](https://user-images.githubusercontent.com/7628901/88452531-8e765480-ce70-11ea-8602-90bb34e3e78d.png)

**Comment by mfaizanatiq** [comment]
@kpachhai  let me know if these designs look ok.

**Comment by kpachhai** [comment]
Looks good
