### ISSUE TITLE
Add instructions on the app on how to use Vouch app

### ISSUE THREAD

**Issue by kpachhai** [tuum-tech/vouch-capsule#63]
Add a tutorial section on home page on how to use Vouch app:
1. Select from the list of available services such as "Email Validation", "Phone Validation", etc
2. Choose your preferred validator 
3. Wait to be verified
4. You can swipe down on the Home page to refresh data
5. Check out "Approved" tab from Requests page to see all your past requests

As part of this issue, also put the above instructions on the onboarding page. Have a "Sign in" button. 

Put a "?" icon on the bottom tab for Help. Clicking this would show the tutorials above.

**Comment by mfaizanatiq** [comment]
### On-Boarding
![image](https://user-images.githubusercontent.com/7628901/88453488-62f76800-ce78-11ea-9105-da6774021637.png)
Keeping a 'How to use vouch?' button that leads to modal dialog with instructions.

----------------------------------------

### 4th Tab "Learning"
![image](https://user-images.githubusercontent.com/7628901/88452665-a5697680-ce71-11ea-96d8-b788cd927fd8.png)

-----------------------------------------

### Learning Tab
![image](https://user-images.githubusercontent.com/7628901/88452673-b5815600-ce71-11ea-9573-adcb302f0742.png)

**Comment by kpachhai** [comment]
Looks good. can we change the name "Learning" to "Help" or "Support"? Because we will be using this tab for other things in the future as well such as more info about vouch, how to contact us, terms and conditions, etc

**Comment by mfaizanatiq** [comment]
![image](https://user-images.githubusercontent.com/7628901/88454792-ed44c980-ce82-11ea-87a7-66ef78d3455f.png)

**Comment by mfaizanatiq** [comment]
This will be Ideal, but I don't know whether this much text can be adjusted

![image](https://user-images.githubusercontent.com/7628901/88454806-06e61100-ce83-11ea-9957-e5606a632cc4.png)

**Comment by mfaizanatiq** [comment]
@kpachhai

**Comment by kpachhai** [comment]
I think we can just go with either just Help or just Support. Having both would be redundant in my opinion. We can go with Support

**Comment by mfaizanatiq** [comment]
Yeah support will be a right language here

**Comment by kpachhai** [comment]
Great. @wakqasahmed you can integrate this design when you are ready
