### ISSUE TITLE
Update the email validation page to show more stats

### ISSUE THREAD

**Issue by kpachhai** [tuum-tech/vouch-capsule#64]
Modify the Email Validation page to show more stats such as the following for each validator:
- Total # of email addresses verified for each type of request: Pending, Waiting for response, Approved, Rejected

Use this REST API to retrieve this value:
curl -H "Authorization: vouch-restapi-secret-key" http://localhost:8080/v1/validationtx/count/provider_id/5f17a02afbe8980577674011

This is already available on REST API

**Comment by wakqasahmed** [comment]
Instead of additional call per provider, I have added the stats in the provider list call, 
https://github.com/tuum-tech/vouch-restapi-backend/issues/18
https://github.com/tuum-tech/vouch-restapi-backend/pull/19

Once it is retrieved the first time, any subsequent changes will be handled locally.

**Comment by mfaizanatiq** [comment]
@kpachhai 
did you mean, you need stats on this page?
![image](https://user-images.githubusercontent.com/7628901/88452169-85d04f00-ce6d-11ea-9265-f88abcbcc10d.png)

**Comment by kpachhai** [comment]
Yes

**Comment by mfaizanatiq** [comment]
@kpachhai 
![image](https://user-images.githubusercontent.com/7628901/88939189-481d5d00-d297-11ea-88e1-7f283aee8bf5.png)

**Comment by mfaizanatiq** [comment]
@kpachhai what do you think about this design?

**Comment by mfaizanatiq** [comment]
My suggestion would be that if we keep the total requests, each validator entertained instead of keeping four values. It would be easier for the user as less there would be less data to read for the user.

**Comment by kpachhai** [comment]
We don't need to show all these values. Just the total requests, approved and rejected is fine.
Also, can we show those stats on multiple lines? Also unique icon next to them to go with each one of them? like check mark, cross, and whatever else.

**Comment by mfaizanatiq** [comment]
![image](https://user-images.githubusercontent.com/7628901/89156294-7c389c80-d57b-11ea-9d47-fa41c6d49086.png)

**Comment by mfaizanatiq** [comment]
![Initiate-Request](https://user-images.githubusercontent.com/7628901/89156471-ccaffa00-d57b-11ea-8a62-74662a00b21a.jpg)

**Comment by mfaizanatiq** [comment]
@kpachhai will this be fine?

**Comment by kpachhai** [comment]
I like this a lot more. Let's go with this @wakqasahmed

**Comment by wakqasahmed** [comment]
Since we are only showing Approved, Rejected and New. Should I count only these statuses in "Total Requests" or total is all the requests a validator has got including Canceled and Expired?
