### ISSUE TITLE
After scanning QR code, the status should be updated upon receiving callback

### ISSUE THREAD

**Issue by wakqasahmed** [tuum-tech/vouch-capsule#66]
This used to work as expected when the feature was first implemented i.e. after scanning QR code the vouch app used to automatically open up with the updated status.

Need to find if the issue is with callback receiving or afterwards.

**Comment by wakqasahmed** [comment]
@rtrapp any update on the fix of this issue?

**Comment by kpachhai** [comment]
Closing as there's a new issue created for Scanner app repo.
