### ISSUE TITLE
Handling cancelled requests

### ISSUE THREAD

**Issue by wakqasahmed** [tuum-tech/vouch-capsule#68]
As per the new changes, there is a new status called cancelled. Need design (similar to other statuses) to accommodate the change.

**Comment by mfaizanatiq** [comment]
Ok, i will update and post it

**Comment by wakqasahmed** [comment]
As per finalized discussion,

We are keeping 

`Cancelling`, `New`  as gray
`Approved` as  green
`Rejected` as  red
`Expired` as dark gray
`In progress` as purple
`Cancelled` as orange

![image](https://user-images.githubusercontent.com/4486133/89861506-1372a500-dbb7-11ea-9249-fe271df7f5b9.png)
