### ISSUE TITLE
Modify the way toast notification works after submission of a request

### ISSUE THREAD

**Issue by kpachhai** [tuum-tech/vouch-capsule#74]
Add a new page after a user submits their request for email validation or phone validation, etc from Vouch App.
Instead of displaying toast notification, the user would be redirected to this new page.
This new page will render the "next steps" for that particular request from the database.
New page will contain the following fields:
- Validator Name, Logo, DID
- User DID
- Validation Type, Validation Value[Eg. Email: kiran@tuum.tech]
- List of steps[Eg. 1) Do this 2) Do that]

Depends on https://github.com/tuum-tech/vouch-restapi-backend/issues/21

If the request is "New", show the following under "Next Steps"
[x] Step 1: Please wait for the validator to accept your request 
[ ] Step 2: Validator has accepted your request
[ ] Step 3: Step x(Retrieve these from the backend and display them)

If the request is "In Progress", show the following under "Next Steps":
[x] Step 1: Please wait for the validator to accept your request
[x] Step 2: Validator has accepted your request
[ ] Step 3: Step x(Retrieve these from the backend and display them)

If the request is "Accepted", show the following under "Next Steps":
[x] Step 1: Please wait for the validator to accept your request
[x] Step 2: Validator has accepted your request
[x] Step 3: Step x(Retrieve these from the backend and display them)

**Comment by kpachhai** [comment]
The REST API is updated. The app should be updated accordingly.

**Comment by mfaizanatiq** [comment]
@kpachhai,
Just one suggestion why not after a certain request is made we take them directly to the request details page instead of this intermediate screen.

Anyway, kindly check the following design, and let me know what are the steps would you like to add here?

![image](https://user-images.githubusercontent.com/7628901/90341364-1aaf0e00-e010-11ea-8071-20a8b324005a.png)

**Comment by kpachhai** [comment]
The request details page will likely not contain next steps section. That's also one route we could take. Instead of creating an intermediate page, we take them to the request details page but depending on the status of the request, we choose to either show/hide "next steps" section.

Also, for each request type for each validator, the next steps content will be different. These more than likely will be bullet points.

**Comment by mfaizanatiq** [comment]
I believe that this would be a good and consistent approach as the information of the next steps will be consistent and also accessible from the request details page.

**Comment by kpachhai** [comment]
👍

**Comment by kpachhai** [comment]
Any update on the design that includes the bulleted points?  @mfaizanatiq

**Comment by mfaizanatiq** [comment]
![image](https://user-images.githubusercontent.com/7628901/91273172-e82eaf00-e78d-11ea-9a0a-c3fedb7e4b0a.png)
