### ISSUE TITLE
Add a feature for validators to register themselves as one of the validators

### ISSUE THREAD

**Issue by kpachhai** [tuum-tech/vouch-capsule#75]
Add a new feature called "Be a validator" that does the following:
- Choose the validation type to register yourself with. Eg. email, phone, etc. The user can select multiple validation types
- Populate the field "manual". This should be set to true if there is no validator node running. This is for the validators who want to verify info of others directly using Vouch
- Populate the field "next_steps". This should be empty if "manual" is set to true. Otherwise, let the user fill in this field with bullet points.
- Redirect the user to "credaccess" screen that will retrieve their DID, name and avatar. These are all mandatory fields
The format of the data that is fed to API should be something like the following:
```
{
    "did": "did:elastos:imxNkhKuuXaefyFKQuzFnkfRdedDVLYmKV",
    "name": "Tuum Tech",
    "logo":"base64image_code_here",
    "validation": {
        "email": {
            "manual": true,
        },
        "phone": {
            "manual": true,
        }
    }
}
```
or 
```
{
    "did": "did:elastos:imxNkhKuuXaefyFKQuzFnkfRdedDVLYmKV",
    "name": "Tuum Tech",
    "logo":"base64image_code_here",
    "validation": {
        "email": {
            "manual": false,
             "next_steps": [
                 "Please check your email for a QR code",
                 "Scan QR code using elastOS",
                 "Wait to be verified"
             ]
        }
    }
}
```
This should call a new REST API endpoint that automatically registers this validator. Make sure to pass in an extra field called "process" and set it to "manual". This will represent that this validator will be signing other people's DID manually directly using Vouch app so it won't have to run a backend Validator node

Once the user submits, the following happens in the backend:
- REST API registers this new validator and inserts a new row in the database with the appropriate fields
More info available at https://github.com/tuum-tech/vouch-restapi-backend/issues/22

Now, whenever a second user tries to verify their name using Vouch, this new validator would show up:
- Upon selecting the type of validation, the user can select this new validator that was added from Vouch app
- This will call our REST API to create a new request in the database 
- Background service should send a notification to the validator(who's also using elastOS) saying a new user has asked their name to be verified by them
- Validator can open up their Vouch app and they'll see the requests made to them
- Upon clicking on any of the requests, it'll use DID SDK to sign the user's name using their own DID[This is similar to a process where a backend validator node would be doing the same thing)
- The validator can then "submit" this signed DID where the user's name is signed by the validator[This is a verified credential]
- This will call our REST API to update the request in the database
- Background service should send a notification to the user saying their name has been validated by the validator
- User can open up their Vouch app and they'll see that the request was signed. The user can now save this verified credential on their Identity capsule

Here's a rough sketch of the new design we need(Feel free to take some liberty):
![vouch update](https://user-images.githubusercontent.com/2739378/93264356-ffe9c980-f774-11ea-95e1-a39f53f6e09c.png)

**Comment by mfaizanatiq** [comment]
![image](https://user-images.githubusercontent.com/7628901/92769110-b3377480-f3a9-11ea-836e-9aff8172c198.png)

![image](https://user-images.githubusercontent.com/7628901/92769130-b7fc2880-f3a9-11ea-803e-ae5431770099.png)

**Comment by mfaizanatiq** [comment]
@kpachhai
