### ISSUE TITLE
Implement a listener for "credverify" intent that lets any caller to open Vouch app

### ISSUE THREAD

**Issue by wakqasahmed** [tuum-tech/vouch-capsule#77]
The example call could be made from Identity app from Email credential under Credentials tab

1. If the email credential is already verified, no action required (and it already shows “Verified by” details)
2. If the email is self-proclaimed, show a button saying “Verify Now” or “Verify” that would show “Continue this action with” and Vouch app in the list of options, upon clicking Vouch option, the Vouch app opens up as normal.

TBD: What happens if user doesn’t have Vouch app installed? @kpachhai

**Comment by kpachhai** [comment]
If vouch app is not installed, or if no other similar app is installed that catches this intent, perhaps, we can show a toast notification that says "No apps available that support verifying credentials"

**Comment by kpachhai** [comment]
So, I just clicked on "Verify now" for my name and I selected Vouch but then it takes me to a white screen.

**Comment by kpachhai** [comment]
Also, "Next Steps" section shouldn't show up on Requests page after the request is no longer in "in-progress" status.

**Comment by wakqasahmed** [comment]
> Also, "Next Steps" section shouldn't show up on Requests page after the request is no longer in "in-progress" status.

Updated the PR

> So, I just clicked on "Verify now" for my random credential(not one of the default fields) and I selected Vouch but then it takes me to a white screen.

This i believe should be fixed via https://github.com/elastos/Elastos.Trinity.DApps.DID/pull/35

**Comment by kpachhai** [comment]
Imagine the following scenario. Would it also fix this issue?
- there's a new field called "University Name" on Identity app
- Vouch app doesn't handle this field

**Comment by wakqasahmed** [comment]
Yep. Try with birthdate or country and see how vouch handles it.
