### ISSUE TITLE
The app gets stuck at splash screen on subsequent open in one case

### ISSUE THREAD

**Issue by wakqasahmed** [tuum-tech/vouch-capsule#79]
If the user opens the app first time but doesn't sign in and closes the app. When he opens the app next time, it gets stuck at splash screen since it has flag onboarded true but no user data found.

It should check both, if onboarded flag is true but user data is missing treat the user as a new user.

**Comment by kpachhai** [comment]
I noticed this behavior too but always forgot to mention
