### ISSUE TITLE
Home page redesign as part of "Register as a Validator"

### ISSUE THREAD

**Issue by wakqasahmed** [tuum-tech/vouch-capsule#85]
Instead of block for each credential type, there needs to be a custom drop down to provide more space and displaying important information without scrolling while implementing [Register as a validator feature](https://github.com/tuum-tech/vouch-capsule/issues/75)

<img width="284" alt="Screen Shot 2020-10-15 at 12 08 46 AM" src="https://user-images.githubusercontent.com/4486133/96040299-19b52400-0e7b-11eb-9752-8739f33efc70.png">

**Comment by wakqasahmed** [comment]
@mfaizanatiq Please provide icons for the following similar to `email` icon shown above. We already have icon for email, phone and name, need it for the rest of the credentials

```
enum CredentialCode {
    EMAIL = "email",
    NAME = "name",
    TELEPHONE = "telephone",
    GENDER = "gender",
    LOCATION = "location",
    BIRTHDATE = "birthdate",
    BIRTHPLACE = "birthplace",
    EDUCATION = "education",
    OCCUPATION = "occupation",
    WECHAT = "wechat",
    INSTAGRAM = "instagram",
    FACEBOOK = "facebook",
    SNAPCHAT = "snapchat",
    TWITTER = "twitter",
    TELEGRAM = "telegram",
    PAYPAL = "paypal",
    ELA = "ela"
}
```

Also, circular icons that are shown under Incoming requests and My requests section.

**Comment by mfaizanatiq** [comment]
Ok

**Comment by mfaizanatiq** [comment]
![image](https://user-images.githubusercontent.com/7628901/99904102-4a8e4180-2ce2-11eb-9b21-9626cf47eb00.png)

I have updated the icons and please use this link for the resources.
https://xd.adobe.com/view/a0432d8b-bc5c-45bb-8b54-5ac8220ae50b-f510/

There is a one i am working on i.e. birthplace will update once done

**Comment by wakqasahmed** [comment]
@mfaizanatiq 

A few more

Twitch
Weibo
Website

Missing ones in previous lot :)

ELA (circular)
Birthplace

**Comment by mfaizanatiq** [comment]
Done have a look
